### ISSUE TITLE
API in local mode 

### ISSUE THREAD

**Issue by berserk14350** [MadPatrick/somfy#10]
Hi,

somfy has open API in local mode. 

it is possible to make a new version of plugin with this mode? I d'ont have a lot of proficiency for this

https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode

But if you want a beta tester! you call me !
thanks a lot

best regards 
berserk

**Comment by JanJaapKo** [comment]
Hi,

I am not going to make the local API version. In fact it should be a different plugin since they are not backwards compatible and can/could be used side by side. So closing the issue here. In the [domoticz form](https://www.domoticz.com/forum/viewtopic.php?p=291586#p291586) some discussion is ongoing to look for volunteers, propose to track it there and keeps this for issues with this implementation only.
